#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "pexisgle_script"
name = "pexisgle-script"
version = "0.1.0"

[build_group]
aulua = "aulua build"

[development]
aviutl2_version = "latest"

[artifacts.t_script-anm2]
destination = "Script/pexisgle/ランダム色で登場.anm2"
source = "build/ランダム色で登場.anm2"
build = { group = "aulua" }

[artifacts.random_placement-anm2]
destination = "Script/pexisgle/個別オブジェクトランダム配置.anm2"
source = "build/個別オブジェクトランダム配置.anm2"
build = { group = "aulua" }

[artifacts.nth_object-anm2]
destination = "Script/pexisgle/個別オブジェクト特定番目表示.anm2"
source = "build/個別オブジェクト特定番目表示.anm2"
build = { group = "aulua" }

[release]
output_dir = "release"
